py.install_sources(
    [
        'class_signal_arrays.py',
        'class_signals.py',
        'class_window_info.py',
        'daq_window.py',
        'main_window.py',
        'qt_workers.py',
        'ui_listdialog.py',
        'ui_mainwindow.py',
        'utils.py',
        'signal_names.py',
        'main.py',
    ],
    subdir: meson.project_name(),
)
