!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.4.4)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinittjii_data_acquisition(f2pysetupfunc)
      use tjii_data_acquisition, only : status
      use tjii_data_acquisition, only : f_lastshot
      use tjii_data_acquisition, only : f_fecha
      use tjii_data_acquisition, only : f_dimenp
      use tjii_data_acquisition, only : f_dimens
      use tjii_data_acquisition, only : f_ertxt
      use tjii_data_acquisition, only : f_getq
      use tjii_data_acquisition, only : f_lectur
      use tjii_data_acquisition, only : f_leep
      use tjii_data_acquisition, only : f_nums
      use tjii_data_acquisition, only : f_listas
      use tjii_data_acquisition, only : f_numshots
      use tjii_data_acquisition, only : f_paramn
      use tjii_data_acquisition, only : f_params
      use tjii_data_acquisition, only : f_sigtype
      use tjii_data_acquisition, only : f_shotlist
      use tjii_data_acquisition, only : f_lectc
      external f2pysetupfunc
      call f2pysetupfunc(status,f_lastshot,f_fecha,f_dimenp,f_dimens,f_e&
     &rtxt,f_getq,f_lectur,f_leep,f_nums,f_listas,f_numshots,f_paramn,f_&
     &params,f_sigtype,f_shotlist,f_lectc)
      end subroutine f2pyinittjii_data_acquisition


