/* File: TJII_data_acquisition_fmodule.c
 * This file is auto-generated with f2py (version:2.4.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Apr 27 19:26:25 2026
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *TJII_data_acquisition_f_error;
static PyObject *TJII_data_acquisition_f_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)


#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(len+1)) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)


/*
STRINGPADN replaces null values with padding values from the right.

`to` must have size of at least N bytes.

If the `to[N-1]` has null value, then replace it and all the
preceding, nulls with the given padding.

STRINGPADN(to, N, PADDING, NULLVALUE) is an inverse operation.
*/
#define STRINGPADN(to, N, NULLVALUE, PADDING)                   \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        for (_m -= 1; _m >= 0 && _to[_m] == NULLVALUE; _m--) {  \
             _to[_m] = PADDING;                                 \
        }                                                       \
    } while (0)


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/*
STRINGCOPYN copies N bytes.

`to` and `from` buffers must have sizes of at least N bytes.
*/
#define STRINGCOPYN(to,from,N)                                  \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, _m);             \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = TJII_data_acquisition_f_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/*
  Create a new string buffer `str` of at most length `len` from a
  Python string-like object `obj`.

  The string buffer has given size (len) or the size of inistr when len==-1.

  The string buffer is padded with blanks: in Fortran, trailing blanks
  are insignificant contrary to C nulls.
 */
static int
string_from_pyobj(string *str, int *len, const string inistr, PyObject *obj,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    string buf = NULL;
    npy_intp n = -1;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",
               (char*)str, *len, (char *)inistr, obj);
#endif
    if (obj == Py_None) {
        n = strlen(inistr);
        buf = inistr;
    }
    else if (PyArray_Check(obj)) {
        PyArrayObject *arr = (PyArrayObject *)obj;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,
                            "array object is non-contiguous.");
            goto capi_fail;
        }
        n = PyArray_NBYTES(arr);
        buf = PyArray_DATA(arr);
        n = strnlen(buf, n);
    }
    else {
        if (PyBytes_Check(obj)) {
            tmp = obj;
            Py_INCREF(tmp);
        }
        else if (PyUnicode_Check(obj)) {
            tmp = PyUnicode_AsASCIIString(obj);
        }
        else {
            PyObject *tmp2;
            tmp2 = PyObject_Str(obj);
            if (tmp2) {
                tmp = PyUnicode_AsASCIIString(tmp2);
                Py_DECREF(tmp2);
            }
            else {
                tmp = NULL;
            }
        }
        if (tmp == NULL) goto capi_fail;
        n = PyBytes_GET_SIZE(tmp);
        buf = PyBytes_AS_STRING(tmp);
    }
    if (*len == -1) {
        /* TODO: change the type of `len` so that we can remove this */
        if (n > NPY_MAX_INT) {
            PyErr_SetString(PyExc_OverflowError,
                            "object too large for a 32-bit int");
            goto capi_fail;
        }
        *len = n;
    }
    else if (*len < n) {
        /* discard the last (len-n) bytes of input buf */
        n = *len;
    }
    if (n < 0 || *len < 0 || buf == NULL) {
        goto capi_fail;
    }
    STRINGMALLOC(*str, *len);  // *str is allocated with size (*len + 1)
    if (n < *len) {
        /*
          Pad fixed-width string with nulls. The caller will replace
          nulls with blanks when the corresponding argument is not
          intent(c).
        */
        memset(*str + n, '\0', *len - n);
    }
    STRINGCOPYN(*str, buf, n);
    Py_XDECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = TJII_data_acquisition_f_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* f_lastshot *********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lastshot[] = "\
ndes,ierr = f_lastshot()\n\nWrapper for ``f_lastshot``.\
\n\nReturns\n-------\n"
"ndes : int\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lastshot(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:TJII_data_acquisition_f.tjii_data_acquisition.f_lastshot",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ndes */
    /* Processing variable ierr */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("ii",ndes,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ierr */
    /* End of cleaning variable ndes */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of f_lastshot *****************************/

/********************************** f_fecha **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_fecha[] = "\
tmp,ierr = f_fecha(ndes)\n\nWrapper for ``f_fecha``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"\nReturns\n-------\n"
"tmp : rank-1 array('i') with bounds (5)\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_fecha(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    int *tmp = NULL;
    npy_intp tmp_Dims[1] = {-1};
    const int tmp_Rank = 1;
    PyArrayObject *capi_tmp_as_array = NULL;
    int capi_tmp_intent = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:TJII_data_acquisition_f.tjii_data_acquisition.f_fecha",\
        capi_kwlist,&ndes_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_fecha() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable tmp */
    tmp_Dims[0]=5;
    capi_tmp_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_fecha: failed to create array from the hidden `tmp`";
    capi_tmp_as_array = ndarray_from_pyobj(  NPY_INT,1,tmp_Dims,tmp_Rank,  capi_tmp_intent,Py_None,capi_errmess);
    if (capi_tmp_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        tmp = (int *)(PyArray_DATA(capi_tmp_as_array));

    /* Processing variable ierr */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,tmp,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("Ni",capi_tmp_as_array,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ierr */
    }  /* if (capi_tmp_as_array == NULL) ... else of tmp */
    /* End of cleaning variable tmp */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of f_fecha *******************************/

/********************************** f_dimenp **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_dimenp[] = "\
nper,npunt,ierr = f_dimenp(ndes,senal)\n\nWrapper for ``f_dimenp``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"senal : input string(len=32)\n"
"\nReturns\n-------\n"
"nper : int\n"
"npunt : int\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_dimenp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int nper = 0;
    int npunt = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","senal",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:TJII_data_acquisition_f.tjii_data_acquisition.f_dimenp",\
        capi_kwlist,&ndes_capi,&senal_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 2nd argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_dimenp to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_dimenp() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable nper */
    /* Processing variable npunt */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,senal,&nper,&npunt,&ierr,slen(senal));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("iii",nper,npunt,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable npunt */
    /* End of cleaning variable nper */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of f_dimenp ******************************/

/********************************** f_dimens **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_dimens[] = "\
ndat,nvent,ierr = f_dimens(ndes,senal)\n\nWrapper for ``f_dimens``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"senal : input string(len=32)\n"
"\nReturns\n-------\n"
"ndat : int\n"
"nvent : int\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_dimens(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int ndat = 0;
    int nvent = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","senal",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:TJII_data_acquisition_f.tjii_data_acquisition.f_dimens",\
        capi_kwlist,&ndes_capi,&senal_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 2nd argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_dimens to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_dimens() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable ndat */
    /* Processing variable nvent */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,senal,&ndat,&nvent,&ierr,slen(senal));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("iii",ndat,nvent,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable nvent */
    /* End of cleaning variable ndat */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of f_dimens ******************************/

/********************************** f_ertxt **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_ertxt[] = "\
f_ertxt(ncode)\n\nWrapper for ``f_ertxt``.\
\n\nParameters\n----------\n"
"ncode : input int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_ertxt(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ncode = 0;
    PyObject *ncode_capi = Py_None;
    static char *capi_kwlist[] = {"ncode",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:TJII_data_acquisition_f.tjii_data_acquisition.f_ertxt",\
        capi_kwlist,&ncode_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ncode */
        f2py_success = int_from_pyobj(&ncode,ncode_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_ertxt() 1st argument (ncode) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ncode);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of ncode*/
    /* End of cleaning variable ncode */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of f_ertxt *******************************/

/*********************************** f_getq ***********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_getq[] = "\
idx,ierr = f_getq(ndes,senal)\n\nWrapper for ``f_getq``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"senal : input string(len=32)\n"
"\nReturns\n-------\n"
"idx : int\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_getq(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int idx = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","senal",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:TJII_data_acquisition_f.tjii_data_acquisition.f_getq",\
        capi_kwlist,&ndes_capi,&senal_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 2nd argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_getq to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_getq() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable idx */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,senal,&idx,&ierr,slen(senal));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("ii",idx,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable idx */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of f_getq *******************************/

/********************************** f_lectur **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lectur[] = "\
x,y,ierr = f_lectur(ndes,senal,ndat,nvent)\n\nWrapper for ``f_lectur``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"senal : input string(len=32)\n"
"ndat : input int\n"
"nvent : input int\n"
"\nReturns\n-------\n"
"x : rank-1 array('f') with bounds (ndat)\n"
"y : rank-1 array('f') with bounds (ndat)\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lectur(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,int*,float*,float*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int ndat = 0;
    PyObject *ndat_capi = Py_None;
    int nvent = 0;
    PyObject *nvent_capi = Py_None;
    float *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    float *y = NULL;
    npy_intp y_Dims[1] = {-1};
    const int y_Rank = 1;
    PyArrayObject *capi_y_as_array = NULL;
    int capi_y_intent = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","senal","ndat","nvent",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:TJII_data_acquisition_f.tjii_data_acquisition.f_lectur",\
        capi_kwlist,&ndes_capi,&senal_capi,&ndat_capi,&nvent_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 2nd argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_lectur to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_lectur() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ndat */
        f2py_success = int_from_pyobj(&ndat,ndat_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_lectur() 3rd argument (ndat) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nvent */
        f2py_success = int_from_pyobj(&nvent,nvent_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_lectur() 4th argument (nvent) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable x */
    x_Dims[0]=ndat;
    capi_x_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_lectur: failed to create array from the hidden `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,x_Dims,x_Rank,  capi_x_intent,Py_None,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (float *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable y */
    y_Dims[0]=ndat;
    capi_y_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_lectur: failed to create array from the hidden `y`";
    capi_y_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,y_Dims,y_Rank,  capi_y_intent,Py_None,capi_errmess);
    if (capi_y_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        y = (float *)(PyArray_DATA(capi_y_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,senal,&ndat,&nvent,x,y,&ierr,slen(senal));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNi",capi_x_as_array,capi_y_as_array,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_y_as_array == NULL) ... else of y */
    /* End of cleaning variable y */
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of nvent*/
    /* End of cleaning variable nvent */
    } /*if (f2py_success) of ndat*/
    /* End of cleaning variable ndat */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of f_lectur ******************************/

/*********************************** f_leep ***********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_leep[] = "\
t,r,y,ierr = f_leep(ndes,senal,nnper,nnpunt)\n\nWrapper for ``f_leep``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"senal : input string(len=32)\n"
"nnper : input int\n"
"nnpunt : input int\n"
"\nReturns\n-------\n"
"t : rank-1 array('f') with bounds (nnper)\n"
"r : rank-2 array('f') with bounds (nnpunt,nnper)\n"
"y : rank-2 array('f') with bounds (nnpunt,nnper)\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_leep(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,int*,float*,float*,float*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int nnper = 0;
    PyObject *nnper_capi = Py_None;
    int nnpunt = 0;
    PyObject *nnpunt_capi = Py_None;
    float *t = NULL;
    npy_intp t_Dims[1] = {-1};
    const int t_Rank = 1;
    PyArrayObject *capi_t_as_array = NULL;
    int capi_t_intent = 0;
    float *r = NULL;
    npy_intp r_Dims[2] = {-1, -1};
    const int r_Rank = 2;
    PyArrayObject *capi_r_as_array = NULL;
    int capi_r_intent = 0;
    float *y = NULL;
    npy_intp y_Dims[2] = {-1, -1};
    const int y_Rank = 2;
    PyArrayObject *capi_y_as_array = NULL;
    int capi_y_intent = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","senal","nnper","nnpunt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:TJII_data_acquisition_f.tjii_data_acquisition.f_leep",\
        capi_kwlist,&ndes_capi,&senal_capi,&nnper_capi,&nnpunt_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_leep() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nnpunt */
        f2py_success = int_from_pyobj(&nnpunt,nnpunt_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_leep() 4th argument (nnpunt) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nnper */
        f2py_success = int_from_pyobj(&nnper,nnper_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_leep() 3rd argument (nnper) can't be converted to int");
    if (f2py_success) {
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 2nd argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_leep to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
    /* Processing variable ierr */
    /* Processing variable r */
    r_Dims[0]=nnpunt,r_Dims[1]=nnper;
    capi_r_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_leep: failed to create array from the hidden `r`";
    capi_r_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,r_Dims,r_Rank,  capi_r_intent,Py_None,capi_errmess);
    if (capi_r_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        r = (float *)(PyArray_DATA(capi_r_as_array));

    /* Processing variable y */
    y_Dims[0]=nnpunt,y_Dims[1]=nnper;
    capi_y_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_leep: failed to create array from the hidden `y`";
    capi_y_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,y_Dims,y_Rank,  capi_y_intent,Py_None,capi_errmess);
    if (capi_y_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        y = (float *)(PyArray_DATA(capi_y_as_array));

    /* Processing variable t */
    t_Dims[0]=nnper;
    capi_t_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_leep: failed to create array from the hidden `t`";
    capi_t_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,t_Dims,t_Rank,  capi_t_intent,Py_None,capi_errmess);
    if (capi_t_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        t = (float *)(PyArray_DATA(capi_t_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,senal,&nnper,&nnpunt,t,r,y,&ierr,slen(senal));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNNi",capi_t_as_array,capi_r_as_array,capi_y_as_array,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_t_as_array == NULL) ... else of t */
    /* End of cleaning variable t */
    }  /* if (capi_y_as_array == NULL) ... else of y */
    /* End of cleaning variable y */
    }  /* if (capi_r_as_array == NULL) ... else of r */
    /* End of cleaning variable r */
    /* End of cleaning variable ierr */
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
    } /*if (f2py_success) of nnper*/
    /* End of cleaning variable nnper */
    } /*if (f2py_success) of nnpunt*/
    /* End of cleaning variable nnpunt */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of f_leep *******************************/

/*********************************** f_nums ***********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_nums[] = "\
nsen,ierr = f_nums(ndes)\n\nWrapper for ``f_nums``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"\nReturns\n-------\n"
"nsen : int\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_nums(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    int nsen = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:TJII_data_acquisition_f.tjii_data_acquisition.f_nums",\
        capi_kwlist,&ndes_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_nums() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nsen */
    /* Processing variable ierr */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,&nsen,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("ii",nsen,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ierr */
    /* End of cleaning variable nsen */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of f_nums *******************************/

/********************************** f_listas **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_listas[] = "\
lista,ierr = f_listas(ndes,nums)\n\nWrapper for ``f_listas``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"nums : input int\n"
"\nReturns\n-------\n"
"lista : rank-1 array('S') with bounds (nums)\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_listas(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,string*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    int nums = 0;
    PyObject *nums_capi = Py_None;
    string *lista = NULL;
    npy_intp lista_Dims[1] = {-1};
    const int lista_Rank = 1;
    PyArrayObject *capi_lista_as_array = NULL;
    int capi_lista_intent = 0;
    int slen(lista) = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","nums",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:TJII_data_acquisition_f.tjii_data_acquisition.f_listas",\
        capi_kwlist,&ndes_capi,&nums_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_listas() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nums */
        f2py_success = int_from_pyobj(&nums,nums_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_listas() 2nd argument (nums) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable lista */
    lista_Dims[0]=nums;
    capi_lista_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_listas: failed to create array from the hidden `lista`";
    capi_lista_as_array = ndarray_from_pyobj(  NPY_STRING,24,lista_Dims,lista_Rank,  capi_lista_intent,Py_None,capi_errmess);
    if (capi_lista_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        lista = (string *)(PyArray_DATA(capi_lista_as_array));

    slen(lista) = f2py_itemsize(lista);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,&nums,lista,&ierr,slen(lista));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("Ni",capi_lista_as_array,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_lista_as_array == NULL) ... else of lista */
    /* End of cleaning variable lista */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of nums*/
    /* End of cleaning variable nums */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of f_listas ******************************/

/********************************* f_numshots *********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_numshots[] = "\
nshots,ierr = f_numshots(ano,mes,dia)\n\nWrapper for ``f_numshots``.\
\n\nParameters\n----------\n"
"ano : input int\n"
"mes : input int\n"
"dia : input int\n"
"\nReturns\n-------\n"
"nshots : int\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_numshots(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ano = 0;
    PyObject *ano_capi = Py_None;
    int mes = 0;
    PyObject *mes_capi = Py_None;
    int dia = 0;
    PyObject *dia_capi = Py_None;
    int nshots = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ano","mes","dia",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:TJII_data_acquisition_f.tjii_data_acquisition.f_numshots",\
        capi_kwlist,&ano_capi,&mes_capi,&dia_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ano */
        f2py_success = int_from_pyobj(&ano,ano_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_numshots() 1st argument (ano) can't be converted to int");
    if (f2py_success) {
    /* Processing variable mes */
        f2py_success = int_from_pyobj(&mes,mes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_numshots() 2nd argument (mes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable dia */
        f2py_success = int_from_pyobj(&dia,dia_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_numshots() 3rd argument (dia) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable nshots */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ano,&mes,&dia,&nshots,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("ii",nshots,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable nshots */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of dia*/
    /* End of cleaning variable dia */
    } /*if (f2py_success) of mes*/
    /* End of cleaning variable mes */
    } /*if (f2py_success) of ano*/
    /* End of cleaning variable ano */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of f_numshots *****************************/

/********************************** f_paramn **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_paramn[] = "\
np,ierr = f_paramn(ndes,senal)\n\nWrapper for ``f_paramn``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"senal : input string(len=32)\n"
"\nReturns\n-------\n"
"np : int\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_paramn(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int np = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","senal",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:TJII_data_acquisition_f.tjii_data_acquisition.f_paramn",\
        capi_kwlist,&ndes_capi,&senal_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_paramn() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable np */
    /* Processing variable ierr */
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 2nd argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_paramn to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,senal,&np,&ierr,slen(senal));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("ii",np,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
    /* End of cleaning variable ierr */
    /* End of cleaning variable np */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of f_paramn ******************************/

/********************************** f_params **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_params[] = "\
prmtos,values,ierr = f_params(ndes,senal,ndimp)\n\nWrapper for ``f_params``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"senal : input string(len=32)\n"
"ndimp : input int\n"
"\nReturns\n-------\n"
"prmtos : rank-1 array('S') with bounds (ndimp)\n"
"values : rank-1 array('f') with bounds (ndimp)\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_params(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,string*,float*,int*,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int ndimp = 0;
    PyObject *ndimp_capi = Py_None;
    string *prmtos = NULL;
    npy_intp prmtos_Dims[1] = {-1};
    const int prmtos_Rank = 1;
    PyArrayObject *capi_prmtos_as_array = NULL;
    int capi_prmtos_intent = 0;
    int slen(prmtos) = 0;
    float *values = NULL;
    npy_intp values_Dims[1] = {-1};
    const int values_Rank = 1;
    PyArrayObject *capi_values_as_array = NULL;
    int capi_values_intent = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","senal","ndimp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:TJII_data_acquisition_f.tjii_data_acquisition.f_params",\
        capi_kwlist,&ndes_capi,&senal_capi,&ndimp_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_params() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ndimp */
        f2py_success = int_from_pyobj(&ndimp,ndimp_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_params() 3rd argument (ndimp) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 2nd argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_params to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
    /* Processing variable prmtos */
    prmtos_Dims[0]=ndimp;
    capi_prmtos_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_params: failed to create array from the hidden `prmtos`";
    capi_prmtos_as_array = ndarray_from_pyobj(  NPY_STRING,16,prmtos_Dims,prmtos_Rank,  capi_prmtos_intent,Py_None,capi_errmess);
    if (capi_prmtos_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        prmtos = (string *)(PyArray_DATA(capi_prmtos_as_array));

    slen(prmtos) = f2py_itemsize(prmtos);
    /* Processing variable values */
    values_Dims[0]=ndimp;
    capi_values_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_params: failed to create array from the hidden `values`";
    capi_values_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,values_Dims,values_Rank,  capi_values_intent,Py_None,capi_errmess);
    if (capi_values_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        values = (float *)(PyArray_DATA(capi_values_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,senal,&ndimp,prmtos,values,&ierr,slen(senal),slen(prmtos));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNi",capi_prmtos_as_array,capi_values_as_array,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_values_as_array == NULL) ... else of values */
    /* End of cleaning variable values */
    }  /* if (capi_prmtos_as_array == NULL) ... else of prmtos */
    /* End of cleaning variable prmtos */
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of ndimp*/
    /* End of cleaning variable ndimp */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of f_params ******************************/

/********************************* f_sigtype *********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_sigtype[] = "\
tipo,ierr = f_sigtype(senal)\n\nWrapper for ``f_sigtype``.\
\n\nParameters\n----------\n"
"senal : input string(len=32)\n"
"\nReturns\n-------\n"
"tipo : int\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_sigtype(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int tipo = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"senal",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:TJII_data_acquisition_f.tjii_data_acquisition.f_sigtype",\
        capi_kwlist,&senal_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 1st argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_sigtype to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
    /* Processing variable tipo */
    /* Processing variable ierr */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(senal,&tipo,&ierr,slen(senal));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("ii",tipo,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ierr */
    /* End of cleaning variable tipo */
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of f_sigtype ******************************/

/********************************* f_shotlist *********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_shotlist[] = "\
shots,ierr = f_shotlist(ano,mes,dia,ndim)\n\nWrapper for ``f_shotlist``.\
\n\nParameters\n----------\n"
"ano : input int\n"
"mes : input int\n"
"dia : input int\n"
"ndim : input int\n"
"\nReturns\n-------\n"
"shots : rank-1 array('i') with bounds (ndim)\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_shotlist(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ano = 0;
    PyObject *ano_capi = Py_None;
    int mes = 0;
    PyObject *mes_capi = Py_None;
    int dia = 0;
    PyObject *dia_capi = Py_None;
    int ndim = 0;
    PyObject *ndim_capi = Py_None;
    int *shots = NULL;
    npy_intp shots_Dims[1] = {-1};
    const int shots_Rank = 1;
    PyArrayObject *capi_shots_as_array = NULL;
    int capi_shots_intent = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ano","mes","dia","ndim",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:TJII_data_acquisition_f.tjii_data_acquisition.f_shotlist",\
        capi_kwlist,&ano_capi,&mes_capi,&dia_capi,&ndim_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ano */
        f2py_success = int_from_pyobj(&ano,ano_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_shotlist() 1st argument (ano) can't be converted to int");
    if (f2py_success) {
    /* Processing variable mes */
        f2py_success = int_from_pyobj(&mes,mes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_shotlist() 2nd argument (mes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable dia */
        f2py_success = int_from_pyobj(&dia,dia_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_shotlist() 3rd argument (dia) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ndim */
        f2py_success = int_from_pyobj(&ndim,ndim_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_shotlist() 4th argument (ndim) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable shots */
    shots_Dims[0]=ndim;
    capi_shots_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_shotlist: failed to create array from the hidden `shots`";
    capi_shots_as_array = ndarray_from_pyobj(  NPY_INT,1,shots_Dims,shots_Rank,  capi_shots_intent,Py_None,capi_errmess);
    if (capi_shots_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        shots = (int *)(PyArray_DATA(capi_shots_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ano,&mes,&dia,&ndim,shots,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("Ni",capi_shots_as_array,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_shots_as_array == NULL) ... else of shots */
    /* End of cleaning variable shots */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of ndim*/
    /* End of cleaning variable ndim */
    } /*if (f2py_success) of dia*/
    /* End of cleaning variable dia */
    } /*if (f2py_success) of mes*/
    /* End of cleaning variable mes */
    } /*if (f2py_success) of ano*/
    /* End of cleaning variable ano */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of f_shotlist *****************************/

/********************************** f_lectc **********************************/
static char doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lectc[] = "\
x,y,ierr = f_lectc(ndes,senal,ndat,nvent)\n\nWrapper for ``f_lectc``.\
\n\nParameters\n----------\n"
"ndes : input int\n"
"senal : input string(len=32)\n"
"ndat : input int\n"
"nvent : input int\n"
"\nReturns\n-------\n"
"x : rank-1 array('f') with bounds (ndat)\n"
"y : rank-1 array('i') with bounds (ndat)\n"
"ierr : int";
/*  */
static PyObject *f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lectc(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,int*,int*,float*,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int ndes = 0;
    PyObject *ndes_capi = Py_None;
    string senal = NULL;
    int slen(senal);
    PyObject *senal_capi = Py_None;
    int ndat = 0;
    PyObject *ndat_capi = Py_None;
    int nvent = 0;
    PyObject *nvent_capi = Py_None;
    float *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    int *y = NULL;
    npy_intp y_Dims[1] = {-1};
    const int y_Rank = 1;
    PyArrayObject *capi_y_as_array = NULL;
    int capi_y_intent = 0;
    int ierr = 0;
    static char *capi_kwlist[] = {"ndes","senal","ndat","nvent",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:TJII_data_acquisition_f.tjii_data_acquisition.f_lectc",\
        capi_kwlist,&ndes_capi,&senal_capi,&ndat_capi,&nvent_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable senal */
    slen(senal) = 32;
    f2py_success = string_from_pyobj(&senal,&slen(senal),"",senal_capi,"string_from_pyobj failed in converting 2nd argument`senal' of TJII_data_acquisition_f.tjii_data_acquisition.f_lectc to C string");
    if (f2py_success) {
        STRINGPADN(senal, slen(senal), '\0', ' ');
    /* Processing variable ndes */
        f2py_success = int_from_pyobj(&ndes,ndes_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_lectc() 1st argument (ndes) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ndat */
        f2py_success = int_from_pyobj(&ndat,ndat_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_lectc() 3rd argument (ndat) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nvent */
        f2py_success = int_from_pyobj(&nvent,nvent_capi,"TJII_data_acquisition_f.tjii_data_acquisition.f_lectc() 4th argument (nvent) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ierr */
    /* Processing variable x */
    x_Dims[0]=ndat;
    capi_x_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_lectc: failed to create array from the hidden `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,x_Dims,x_Rank,  capi_x_intent,Py_None,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (float *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable y */
    y_Dims[0]=ndat;
    capi_y_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "TJII_data_acquisition_f.TJII_data_acquisition_f.tjii_data_acquisition.f_lectc: failed to create array from the hidden `y`";
    capi_y_as_array = ndarray_from_pyobj(  NPY_INT,1,y_Dims,y_Rank,  capi_y_intent,Py_None,capi_errmess);
    if (capi_y_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = TJII_data_acquisition_f_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        y = (int *)(PyArray_DATA(capi_y_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&ndes,senal,&ndat,&nvent,x,y,&ierr,slen(senal));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNi",capi_x_as_array,capi_y_as_array,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_y_as_array == NULL) ... else of y */
    /* End of cleaning variable y */
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
    /* End of cleaning variable ierr */
    } /*if (f2py_success) of nvent*/
    /* End of cleaning variable nvent */
    } /*if (f2py_success) of ndat*/
    /* End of cleaning variable ndat */
    } /*if (f2py_success) of ndes*/
    /* End of cleaning variable ndes */
        STRINGFREE(senal);
    }  /*if (f2py_success) of senal*/
    /* End of cleaning variable senal */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of f_lectc *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_tjii_data_acquisition_def[] = {
  {"status",0,{{-1}},NPY_INT, 1},
  {"f_lastshot",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lastshot,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lastshot},
  {"f_fecha",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_fecha,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_fecha},
  {"f_dimenp",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_dimenp,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_dimenp},
  {"f_dimens",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_dimens,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_dimens},
  {"f_ertxt",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_ertxt,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_ertxt},
  {"f_getq",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_getq,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_getq},
  {"f_lectur",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lectur,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lectur},
  {"f_leep",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_leep,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_leep},
  {"f_nums",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_nums,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_nums},
  {"f_listas",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_listas,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_listas},
  {"f_numshots",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_numshots,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_numshots},
  {"f_paramn",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_paramn,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_paramn},
  {"f_params",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_params,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_params},
  {"f_sigtype",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_sigtype,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_sigtype},
  {"f_shotlist",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_shotlist,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_shotlist},
  {"f_lectc",-1,{{-1}},0,0,NULL,(void *)f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lectc,doc_f2py_rout_TJII_data_acquisition_f_tjii_data_acquisition_f_lectc},
  {NULL}
};

static void f2py_setup_tjii_data_acquisition(char *status,char *f_lastshot,char *f_fecha,char *f_dimenp,char *f_dimens,char *f_ertxt,char *f_getq,char *f_lectur,char *f_leep,char *f_nums,char *f_listas,char *f_numshots,char *f_paramn,char *f_params,char *f_sigtype,char *f_shotlist,char *f_lectc) {
  int i_f2py=0;
  f2py_tjii_data_acquisition_def[i_f2py++].data = status;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_lastshot;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_fecha;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_dimenp;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_dimens;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_ertxt;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_getq;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_lectur;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_leep;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_nums;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_listas;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_numshots;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_paramn;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_params;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_sigtype;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_shotlist;
  f2py_tjii_data_acquisition_def[i_f2py++].data = f_lectc;
}
extern void F_FUNC_US(f2pyinittjii_data_acquisition,F2PYINITTJII_DATA_ACQUISITION)(void (*)(char*,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_tjii_data_acquisition(void) {
  F_FUNC_US(f2pyinittjii_data_acquisition,F2PYINITTJII_DATA_ACQUISITION)(f2py_setup_tjii_data_acquisition);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "TJII_data_acquisition_f",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_TJII_data_acquisition_f(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = TJII_data_acquisition_f_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module TJII_data_acquisition_f (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.4.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'TJII_data_acquisition_f' is auto-generated with f2py (version:2.4.4).\nFunctions:\n"
"Fortran 90/95 modules:\n""  tjii_data_acquisition --- status,f_lastshot(),f_fecha(),f_dimenp(),f_dimens(),f_ertxt(),f_getq(),f_lectur(),f_leep(),f_nums(),f_listas(),f_numshots(),f_paramn(),f_params(),f_sigtype(),f_shotlist(),f_lectc()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.4.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    TJII_data_acquisition_f_error = PyErr_NewException ("TJII_data_acquisition_f.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_TJII_data_acquisition_f_error", TJII_data_acquisition_f_error);
    Py_DECREF(TJII_data_acquisition_f_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }
















/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "tjii_data_acquisition", PyFortranObject_New(f2py_tjii_data_acquisition_def,f2py_init_tjii_data_acquisition));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"TJII_data_acquisition_f");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
